export const PERMISSIONS = [
  'product:view',
  'product:create',
  'product:edit',
  'product:delete',
  'product:import',
  'product:export',
  'product:status',
  'product:clone',
  'category:view',
  'category:create',
  'category:edit',
  'category:delete',
  'brand:view',
  'brand:create',
  'brand:edit',
  'brand:delete',
  'tag:view',
  'tag:create',
  'tag:edit',
  'tag:delete',
  'supplier:view',
  'supplier:create',
  'supplier:edit',
  'supplier:delete',
  'user:view',
  'user:create',
  'user:edit',
  'user:delete',
  'role:view',
  'role:create',
  'role:edit',
  'role:delete',
  'role:assign',
  'proposal:view',
  'proposal:create',
  'proposal:edit',
  'proposal:delete',
  'quotation:view',
  'quotation:create',
  'quotation:edit',
  'quotation:delete',
  'share:view',
  'share:create',
  'share:delete',
  'file:view',
  'file:upload',
  'file:delete',
  'media:view',
  'media:upload',
  'media:delete',
  'media:replace',
  'scene_image:view',
  'scene_image:create',
  'scene_image:edit',
  'scene_image:delete',
  'stats:view',
  'ai:use',
] as const

export type PermissionCode = (typeof PERMISSIONS)[number]

export function hasPermission(permissions: string[], perm: PermissionCode | string): boolean {
  return permissions.includes(perm)
}

export function hasAnyPermission(permissions: string[], perms: (PermissionCode | string)[]): boolean {
  return perms.some((p) => permissions.includes(p))
}

export function hasAllPermissions(permissions: string[], perms: (PermissionCode | string)[]): boolean {
  return perms.every((p) => permissions.includes(p))
}

export const RESOURCE_PERMISSIONS: Record<string, PermissionCode[]> = {
  product: ['product:view', 'product:create', 'product:edit', 'product:delete', 'product:import', 'product:export', 'product:status', 'product:clone'],
  category: ['category:view', 'category:create', 'category:edit', 'category:delete'],
  brand: ['brand:view', 'brand:create', 'brand:edit', 'brand:delete'],
  tag: ['tag:view', 'tag:create', 'tag:edit', 'tag:delete'],
  supplier: ['supplier:view', 'supplier:create', 'supplier:edit', 'supplier:delete'],
  user: ['user:view', 'user:create', 'user:edit', 'user:delete'],
  role: ['role:view', 'role:create', 'role:edit', 'role:delete', 'role:assign'],
  proposal: ['proposal:view', 'proposal:create', 'proposal:edit', 'proposal:delete'],
  quotation: ['quotation:view', 'quotation:create', 'quotation:edit', 'quotation:delete'],
  share: ['share:view', 'share:create', 'share:delete'],
  file: ['file:view', 'file:upload', 'file:delete'],
  media: ['media:view', 'media:upload', 'media:delete', 'media:replace'],
  scene_image: ['scene_image:view', 'scene_image:create', 'scene_image:edit', 'scene_image:delete'],
  stats: ['stats:view'],
  ai: ['ai:use'],
}

export const PERMISSION_NAMES: Record<PermissionCode, string> = {
  'product:view': '产品查看',
  'product:create': '产品新增',
  'product:edit': '产品编辑',
  'product:delete': '产品删除',
  'product:import': '产品导入',
  'product:export': '产品导出',
  'product:status': '产品上下架',
  'product:clone': '产品克隆',
  'category:view': '品类查看',
  'category:create': '品类新增',
  'category:edit': '品类编辑',
  'category:delete': '品类删除',
  'brand:view': '品牌查看',
  'brand:create': '品牌新增',
  'brand:edit': '品牌编辑',
  'brand:delete': '品牌删除',
  'tag:view': '标签查看',
  'tag:create': '标签新增',
  'tag:edit': '标签编辑',
  'tag:delete': '标签删除',
  'supplier:view': '供应商查看',
  'supplier:create': '供应商新增',
  'supplier:edit': '供应商编辑',
  'supplier:delete': '供应商删除',
  'user:view': '用户查看',
  'user:create': '用户新增',
  'user:edit': '用户编辑',
  'user:delete': '用户删除',
  'role:view': '角色查看',
  'role:create': '角色新增',
  'role:edit': '角色编辑',
  'role:delete': '角色删除',
  'role:assign': '角色授权',
  'proposal:view': '方案查看',
  'proposal:create': '方案新增',
  'proposal:edit': '方案编辑',
  'proposal:delete': '方案删除',
  'quotation:view': '报价查看',
  'quotation:create': '报价新增',
  'quotation:edit': '报价编辑',
  'quotation:delete': '报价删除',
  'share:view': '分享查看',
  'share:create': '分享创建',
  'share:delete': '分享删除',
  'file:view': '文件查看',
  'file:upload': '文件上传',
  'file:delete': '文件删除',
  'media:view': '媒体库查看',
  'media:upload': '媒体库上传',
  'media:delete': '媒体库删除',
  'media:replace': '媒体库替换',
  'scene_image:view': '场景图查看',
  'scene_image:create': '场景图新增',
  'scene_image:edit': '场景图编辑',
  'scene_image:delete': '场景图删除',
  'stats:view': '统计查看',
  'ai:use': 'AI 能力使用',
}
